spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.wihdcqujnfdyimbblkqb
spring.datasource.password=k48Ra7XbrHVoyWXp

server.port=${PORT:8080}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1